### ISSUE TITLE
Error when using jumpURL v9.0 and mediaessenz/mail v3.7

### ISSUE THREAD

**Issue by mkiebele** [FriendsOfTYPO3/jumpurl#62]
When calling the mail wizard in a TYPO3 instance that works with jumpURL version 9.0 and mediaessenz/mail version 3.7, the following error occurs:
`Too few arguments to function TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::__construct(), 0 passed in /var/www/html/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php on line 2992 and exactly 5 expected`

```
at TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController')
in /var/www/html/vendor/friendsoftypo3/jumpurl/Classes/TypoLink/LinkModifier.php line 224

            $language = $site->getDefaultLanguage();
        }
        $request = $request->withAttribute('language', $language);

        $this->typoScriptFrontendController = GeneralUtility::makeInstance(TypoScriptFrontendController::class);
        $this->typoScriptFrontendController->initializePageRenderer($request);
        $this->typoScriptFrontendController->initializeLanguageService($request);
        return $this->typoScriptFrontendController;
    }
```
When I downgrade to 8.2.2, the error resolves.

**Comment by joeschi** [comment]
Same error here with jumpurl 9 (Typo3 12 and mediaessenz/mail v3.9). 
Just opened a ticket here: https://gitlab.com/mediaessenz/mail/-/issues/111
